huggingface_id: Qwen/Qwen3-4B
model_type: qwen3
pretrained: true
supports_system_prompt: true
max_context_length: 40960
num_hidden_layers: 36
hidden_size: 2560
num_attention_heads: 32
num_key_value_heads: 8
intermediate_size: 9728
vocab_size: 151936
sae:
  available: false
